### ISSUE TITLE
Search Results Page shows the latest description input not the first

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#10]
This is a customization.

**Comment by lucyfj** [comment]
We are entering 3 descriptions with different description types, but when you enter them in the correct order, (History, Site Contents, Excavation), the Search results page  shows the last description entered - Excavation. It should show the first description input, or to be more precise the first description in the  order in the drop down list.  It is possible that we will not always have all 3 descriptions for the site.

The Resource Report shows them in the correct order. (If we tried a work around of inputting the descriptions in the reverse order, the search results are correct but now the Resource report is wrong!)

This is the description type drop down list:
![searchresults_descriptionproblem_typedropdown](https://user-images.githubusercontent.com/16820044/30635212-0443bbba-9df2-11e7-9b3e-eaca54bab611.PNG)

This is the input of the descriptions in normal order:
![searchresults_descriptionproblem3](https://user-images.githubusercontent.com/16820044/30634294-dbb053aa-9dee-11e7-9016-99ad495d442c.PNG)

This is the search results showing the last description (Exploration & excavation) wrongly:


![searchresults_descriptionproblem_searcherror2](https://user-images.githubusercontent.com/16820044/30635511-e6f3af56-9df2-11e7-9db3-0097b19376dc.PNG)


This is the resource report showing descriptions in correct order:

![searchresults_descriptionproblem_reportcorrect](https://user-images.githubusercontent.com/16820044/30635317-521bb5d6-9df2-11e7-99b1-d4e2a2d113eb.PNG)

**Comment by lucyfj** [comment]
It is important to display the first description encountered  when checking in the order of the drop down list because we will be using other headings, such as 'General Description' for some sites. The mod needs to be done for archaeological complexes and archaeological sites.

**Comment by lucyfj** [comment]
![search_desc_alphabet_error](https://user-images.githubusercontent.com/16820044/33834763-bbe187b8-de8c-11e7-8086-994dba8c5c62.PNG)
Sorry but this is not working. See screen print below. Tawd  and Abu Sha'ar are correct but the other 2 sites are showing the latest description entered.

**Comment by mradamcox** [comment]
Please see my [comment on #3](https://github.com/mradamcox/ead/issues/3#issuecomment-350788093).

**Comment by lucyfj** [comment]
Tested again and now the descriptions are showing in the correct order. Thank you!
