### ISSUE TITLE
Archaeological Complex report

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#11]
This is a customization. Change the report to include all new nodes such as , ruler (call it 'reign') and dynasty in classifications. Also sort the report in the same order as for the archaeological site and exclude the many 'none defined' statements in the absence of data. The location lat/long coordinates should be for the Arches centre point of the complex, as these will be polygons or lines. Please also add these coordinates in degrees decimal (lat/long) as it is so much easier having both. Change the 'titles' on the reports as shown.

Here is the print PDF of the report showing the mods:
[ComplexReport_mods.pdf](https://github.com/mradamcox/ead/files/1375076/ComplexReport_mods.pdf)

Please ensure that under 'Related Resources', the order is Related Sites, Related Documents and Related Images.

**Comment by lucyfj** [comment]
By the way, the Archaeological Site (E18) Printed version of the report does not include 'Related Documents', but they are shown on the online version. Please could you correct this and change the order so that Related Documents are after Related Sites and Related Images are last?

This is the print PDF omitting Related Documents
[ArchSiteReport Related docs_error.pdf](https://github.com/mradamcox/ead/files/1375099/ArchSiteReport.Related.docs_error.pdf)

This is the online report showing the documents - bibliographies- after the images. But would like them before.
![archsiteonlinereportcorrect](https://user-images.githubusercontent.com/16820044/31434200-faa4eab2-ae7b-11e7-9a40-2989da7ea806.PNG)


Thank you very much,
Lucy

**Comment by mradamcox** [comment]
All changes have been made and are in the master branch now. A couple of notes:

- parcels hidden in both site and complex reports if they aren't defined
- ruler replaced with reign on both site and complex reports
- removed "deities associated with this site" from information resource
- I didn't encounter the printing error with the test resources I had in place

**Comment by lucyfj** [comment]
I have checked this issue fairly thoroughly and unfortunately there are still some problems:

-  Complex report does not show the complex site type, shows 'undefined'.
-  Complex report repeats the site description. Please keep the one at the beginning of the report and 
   remove the other called 'resource description'. 

I will close and reopen with on-going issues.
