### ISSUE TITLE
Map View default layers

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#12]
Customization. Please change the default layer to showing the archaeological site and Complex layers in different colours, not all resources. It looks much prettier this way!! I believe it will be more useful.

![maplayerscustomization](https://user-images.githubusercontent.com/16820044/30641272-bcf7965e-9e06-11e7-97a2-b99cfd337f5c.PNG)

The site is Saudi Arabia is wrong!

**Comment by lucyfj** [comment]
Thank you very much, it is working very well. My only problem is that it would be useful to have this on the mp in the search pane too. Would this be a lot of extra effort?

**Comment by mradamcox** [comment]
I looked into it and it would be at least an extra hour. So I will keep in it mind in case I have some leftover time, but I can't guarantee I would get to it. Thanks for testing this out :)

**Comment by lucyfj** [comment]
No problems. There may be some money left out of the grant so I will ask Dr. Weeks when we see him next week if we can do some more work on Arches. 
Should I put the map changes on the production system or wait until they are all done?
Lucy

**Comment by mradamcox** [comment]
I think that is up to you. If you want practice in the workflow, this would be a good opportunity because they are very simple changes. In general, it would probably be best to wait to the end, but with something like this there should be no complications.

**Comment by mradamcox** [comment]
@lucyfj if the changes that have been made satisfy this ticket, could you please close it? I see the new ticket for map layers in the search page, so no work on that task should be considered in the evaulation of this ticket.
