### ISSUE TITLE
Map Pop-up extras and lat/long display

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#15]
On checking site locations I have found it essential that we report the location of a site in degrees decimal, in addition to the Degrees, Minutes and Seconds in the map pop-up that is displayed on both the map in 'map view' and on the map in 'Search', when selecting a site.

2. It would also make our lives a lot easier if the map on 'map view' could display the latitude followed by longitude, which is the normal geographic convention. I assume this is a simple display format change and will not involve changes in calculations.

**Comment by mradamcox** [comment]
I took care of this while addressing #8

**Comment by lucyfj** [comment]
The first part is definitely fixed. 

It would still be helpful if the map in map view could display the coordinates (at bottom of the page) as latitude followed by longitude. I shall open as separate issue.

**Comment by mradamcox** [comment]
Ok, just pushed a commit to fix that, apologies for missing that earlier.
