### ISSUE TITLE
Archaeological Complex report - remaining problems

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#22]
There are still the following outstanding errors on this report: 
. The site type for a complex is not shown - shows 'none defined'. Need to check using correct classification group type. 
.  The resource description is still being shown when we already have a 'site description' higher up in the report. Please remove the lower 'resource description' 

Thank you very much.

![complexclass_2reporterror](https://user-images.githubusercontent.com/16820044/34719739-95333a5c-f544-11e7-95e4-b2424a3364b6.PNG)
![complexclass_1input](https://user-images.githubusercontent.com/16820044/34719740-95558ca6-f544-11e7-8b54-df3956ff8b9f.PNG)

**Comment by mradamcox** [comment]
This should be solved now.

**Comment by lucyfj** [comment]
Thank you for doing this so fat. It s fixed!
