### ISSUE TITLE
Search Results Alphabetical order - remaining issue

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#23]
There is still the following outstanding problem:
. Where the primary name of the site is composed of more than one name, it is not in alphabetical order. 

![searchlist_alphaproblem](https://user-images.githubusercontent.com/16820044/34721094-0bbfe1ac-f54a-11e7-9aba-2be244fc7d63.PNG)

Thank you very much.

**Comment by mradamcox** [comment]
closing in favor of reopening the original one.
