### ISSUE TITLE
Resource Reports not always showing primary name first

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#5]
The Resource reports for archaeological site and archaeological complex do not always show the primary name first.  it would be nice if they could. 

![report_primarynameerror](https://user-images.githubusercontent.com/16820044/29749827-3dbebfc2-8b35-11e7-960e-d224cf864fc2.PNG)

**Comment by lucyfj** [comment]
Have decided this is a customisation so will close issue..

**Comment by mradamcox** [comment]
Hi Lucy, it is a customization, but I think it's a fair issue to track.
It's definitely doable, so I'd recommend reopening it, just to keep it in
mind.

**Comment by lucyfj** [comment]
OK, I've reopened it!

**Comment by lucyfj** [comment]
This is now working! Thank you!
