### ISSUE TITLE
Search Screen: export results to .csv  causes key error

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#6]
O
![saerchkeyerrorexportresult](https://user-images.githubusercontent.com/16820044/29749872-ef92ee76-8b35-11e7-83d5-47af572d647b.PNG)
n Export Results to .csv file, key error results.

**Comment by lucyfj** [comment]
This obviously cannot be left like this, but I can't remember what data was exported and I'm not sure how useful it is to us. Could you tell me what most users use this for? I looked at it before and seem to remember that only a few fields are exported. Can it be used to create an Arches file if we ever wish to upgrade to V4.0?

**Comment by mradamcox** [comment]
A .arches file is made with the command line. Exporting a csv like this (which, yeah, needs to be fixed!) will essentially make a spreadsheet with a predefined set of fields.
