### ISSUE TITLE
Location form input

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#7]
On Downsizing the window (which we use all the time for input) the grid reference box is shown twice. This does not disrupt input but would be less confusing if removed. 

![location form_dup gridref box](https://user-images.githubusercontent.com/16820044/29749953-0ffc2154-8b37-11e7-9840-4b332a62e3ae.PNG)

**Comment by lucyfj** [comment]
Lucy will attempt this one.

**Comment by mradamcox** [comment]
I had a few extra minutes and decided to fix this up. It was weird that it wasn't working before...
