### ISSUE TITLE
Sort Search Results Alphabetically

### ISSUE THREAD

**Issue by mradamcox** [legiongis/ead#9]
Search results should be returned in alphabetical order based on primary name.

Preliminary testing showed that added the following

```
    self.dsl['sort'] = [
            {"primaryname" : {"order" : "asc"}}
        ]
```

to the end of [this function](https://github.com/archesproject/arches/blob/stable/3.x/arches/app/search/elasticsearch_dsl_builder.py#L62) does the trick.

**Comment by lucyfj** [comment]
As we are short of time and budget we will not continue with this customization!

**Comment by mradamcox** [comment]
Reopening because it sounds like Andrea Zerbini has the code already to go. Should be a breeze and big thanks to him!

**Comment by lucyfj** [comment]
Still not always in alphabetical order: see screen print below. Abu Aggag should be first.

![search_desc_alphabet_error](https://user-images.githubusercontent.com/16820044/33834552-f7dad5ae-de8b-11e7-9866-b6bcf3d7a573.PNG)

**Comment by mradamcox** [comment]
@lucy, I see what you mean. I have looked more into ElasticSearch sorting and found this documentation: https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-fields.html. It seems that to properly sort the names we would have to add another field to the ES mappings that essentially analyze the name without spaces in it, and then use that field for sorting. Unfortunately, I am not going to be able to do all of that at this time. I will keep it on the back burner for now, and will also ask Andrea if he fixed this issue with the EAMENA search capabilities. Thanks for testing this thoroughly.

**Comment by lucyfj** [comment]
Hi Adam,
Take all the time you need. There's no urgency, as we are all taking a long break after the hard work for the report. There are many sites with more than one word as part of the primary name and we have commas in the name too. 
When we move the changes to the production system, I can send you a CSV file with some of our data if you would like - now that works!

**Comment by mradamcox** [comment]
yes, sending me some test data would be great actually. thanks!

**Comment by mradamcox** [comment]
removing this from the milestone, as it is potentially part of a later upgrade effort.
